#!/bin/bash
cd ./projects
if [ -z "$1" ]; then
    for proj in *; do
        ng build $proj
        cp ../dist/$proj/bundles/*.* ../src/assets/dist/.
    done
else
    ng build $1
    cp ../dist/$1/bundles/*.* ../src/assets/dist/.
fi
