ng build customize
copy ./dist/customize/bundles/*.* ./src/assets/dist/.
ng build log
copy ./dist/log/bundles/*.* ./src/assets/dist/.
ng build lookup
copy ./dist/lookup/bundles/*.* ./src/assets/dist/.
ng build meeting
copy ./dist/meeting/bundles/*.* ./src/assets/dist/.
ng build project
copy ./dist/project/bundles/*.* ./src/assets/dist/.
ng build report
copy ./dist/report/bundles/*.* ./src/assets/dist/.
ng build scheduler
copy ./dist/scheduler/bundles/*.* ./src/assets/dist/.
ng build setting
copy ./dist/setting/bundles/*.* ./src/assets/dist/.
ng build support
copy ./dist/support/bundles/*.* ./src/assets/dist/.
ng build task
copy ./dist/task/bundles/*.* ./src/assets/dist/.
ng build user
copy ./dist/user/bundles/*.* ./src/assets/dist/.
